version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: example-nginx
    restart: unless-stopped
    working_dir: /app
    ports:
      - 20080:80 # frontend
      - 20081:81 # backend
      - 20082:82 # storage
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d:cached
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db
    networks:
      - example

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: example-php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./:/app:cached
    links:
      - db
    depends_on:
      - db
    networks:
      - example

  db:
    #    image: postgres:12.2-alpine
    image: mysql:5.7
    restart: unless-stopped
    ports:
      #      - 5432:5432
      - 3306:3306
    volumes:
      #      - ./docker/storage/psql:/var/lib/postgresql/data:cached
      - ./docker/storage/mysql:/var/lib/mysql:cached
    environment:
      #      POSTGRES_USER: example
      #      POSTGRES_PASSWORD: example
      #      POSTGRES_DB: example
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    networks:
      - example


networks:
  example:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.231.0/28
