version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: crrt-nginx
    restart: unless-stopped
    working_dir: /app
    ports:
      - 20080:80 # frontend
      - 20081:81 # backend
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      # Mount config for development
      - ./docker/nginx:/etc/nginx/conf.d:cached
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db
    networks:
      - crrt

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: crrt-php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./:/app:cached
    links:
      - db
    depends_on:
      - db
    networks:
      - crrt

  db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    ports:
      - 40002:5432
    volumes:
      - ./docker/storage/psql:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: crrt
      POSTGRES_PASSWORD: crrt
      POSTGRES_DB: crrt
    networks:
      - crrt

networks:
  crrt:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.231.0/28
